name: Cross-Platform Workflow

on: 
  push:
    tags:
      - 'test*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout recaster
        uses: actions/checkout@v2
        with:
          repository: impleotv/recaster
          token: ${{ secrets.RECASTER_REPO_TOKEN }}
          path: ./recaster

      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}


      - uses: actions/upload-artifact@v2
        with:
          name: recasterArchive
          path: ./recaster/package.json


  windows-job:
    runs-on: windows-latest
    needs: ubuntu-job

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: recasterArchive

      
      - name: List files in the repository on Windows
        shell: powershell
        run: |
          Get-ChildItem -Path $Env:GITHUB_WORKSPACE -Recurse



      - name: List artifacts
        run: |
          Get-ChildItem -Path $env:GITHUB_WORKSPACE\recasterArchive

      - name: Delete artifact
        run: |
          Remove-Item -Recurse -Force $env:GITHUB_WORKSPACE\recasterArchive

