name: Cross-Platform Workflow

on:
  push:
    branches:
      - main

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout recaster
        uses: actions/checkout@v2
        with:
          repository: impleotv/recaster
          token: ${{ secrets.RECASTER_REPO_TOKEN }}
          path: ./recaster       
    
      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}

      - name: Pass folder to Windows job
        id: pass-folder
        run: echo "::set-output name=folder_path::./recaster"

  windows-job:
    runs-on: windows-latest
    needs: ubuntu-job

    steps:
      - name: Create zip file
        run: |
          $folderPath = $env:INPUT_FOLDER_PATH
          Compress-Archive -Path $folderPath -DestinationPath output.zip

      - name: Upload zip file
        uses: actions/upload-artifact@v2
        with:
          name: recaster-zip
          path: output.zip

  final-job:
    runs-on: ubuntu-latest
    needs: windows-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download zip file
        uses: actions/download-artifact@v2
        with:
          name: recaster-zip

      - name: Extract zip file
        run: unzip recaster-zip -d ./recaster

      - name: Display folder structure
        run: tree ./recaster
