name: OnPushNewVersion

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout recaster
        uses: actions/checkout@v2
        with:
          repository: impleotv/recaster
          token: ${{ secrets.RECASTER_REPO_TOKEN }}
          path: ./recaster       
    
      # - name: List files in the repository
      #   run: |
      #     tree ${{ github.workspace }}

      - name: Setup NodeJs 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install mkdocs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-macros-plugin

      - name: Install dependencies
        run: cd ./recaster && npm install

      - name: Build Recaster
        run: cd ./recaster && npm run build

      - name: Create archive and copy
        run: |
          cd ./recaster/dist
          tar -czvf ../../recaster.tar.gz . 
          

      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}

      - name: Create release    
        uses: ncipollo/release-action@v1
        with:
          artifacts: "recaster.tar.gz"       
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Check version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}   
              
#      - name: Generate README file
#        run: cd .. && node index.js ${{env.RELEASE_VERSION }}

#      - name: Clean up
#        run: |
#          rm -rf ./components

 #     - name: Commit and Push new README.md to the repository
 #       uses: mikeal/publish-to-github-action@master
 #       env:
 #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Create release    
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "recaster.tar.gz, CHANGELOG.md"       
#          token: ${{ secrets.GITHUB_TOKEN }}
        
