name: Cross-Platform Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout recaster
        uses: actions/checkout@v2
        with:
          repository: impleotv/recaster
          token: ${{ secrets.RECASTER_REPO_TOKEN }}
          path: ./recaster

      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}

      - name: Display folder path
        run: echo "Folder Path: ${{ github.workspace }}/recaster"

      - name: Set folder path output
        id: pass-folder
        run: echo "::set-output name=folder_path::${{ github.workspace }}/recaster"

  windows-job:
    runs-on: windows-latest
    needs: ubuntu-job

    steps:
      - name: Set folder path variable
        id: set-folder-path
        run: echo "Folder Path: ${{ needs.ubuntu-job.outputs.folder_path }}"

      - name: Create zip file
        run: |
          $folderPath = $env:INPUT_FOLDER_PATH
          echo "Folder Path in Windows: $folderPath"
          Compress-Archive -Path $folderPath -DestinationPath output.zip

      - name: Upload zip file
        uses: actions/upload-artifact@v2
        with:
          name: recaster-zip
          path: output.zip

  final-job:
    runs-on: ubuntu-latest
    needs: windows-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download zip file
        uses: actions/download-artifact@v2
        with:
          name: recaster-zip

      - name: Extract zip file
        run: unzip recaster-zip -d ./recaster

      - name: Display folder structure
        run: tree ./recaster
