name: OnTest

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:

      - name: Install jq, unzip and 7zip
        run: |
          sudo apt-get install jq
          sudo apt-get install p7zip-full

      - name: Get tag name
        id: get_tag
        run: |
          TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})
          echo "Tag name is: $TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Checkout recaster
        uses: actions/checkout@v4
        with:
          repository: impleotv/recaster
          token: ${{ secrets.RECASTER_REPO_TOKEN }}
          ref: ${{ env.TAG_NAME }}
          path: ./recaster       
          
      - name: Get Stanag2WebRtc release information
        id: get_release
        run: |
          tag_name="v2.0.0"
          release_info=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/impleotv/stanag2webrtc-release/releases/tags/$tag_name")
          release_id=$(echo $release_info | jq -r '.id')
          asset_url_linux=$(echo $release_info | jq -r '.assets[] | select(.name == "linuxDist.tar.gz") | .browser_download_url') 
          echo "URL_LINUX=$(echo $asset_url_linux)" >> $GITHUB_ENV
          asset_url_win=$(echo $release_info | jq -r '.assets[] | select(.name == "winDist.tar.gz") | .browser_download_url')   
          echo "URL_WIN=$(echo $asset_url_win)" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
      - name: Display URLs
        run: |
          echo "Linux URL: $URL_LINUX"
          echo "Windows URL: $URL_WIN"

# -----------------------------------------------
      - name: Download linuxDist.tar.gz
        run: |
          cd ./recaster        
          wget $URL_LINUX -O linuxDist.tar.gz
   
    
      - name: List files in the repository
        run: |
          tree -L 2 ${{ github.workspace }}

      - name: Extract LinuxDist.tar.gz
        run: cd ./recaster && mkdir -p ./Stanag2WebRtc/linux-x64 && tar -xzf ./linuxDist.tar.gz -C ./Stanag2WebRtc/linux-x64 --strip-components=1

 #     - name: Create Linux Release
 #       run: cd ./recaster && npm run create-installLinux

          
# --------------------------------------------
      - name: Download winDist.tar.gz
        run: |
          cd ./recaster 
          wget $URL_WIN -O winDist.tar.gz
    
      - name: List files in the repository
        run: |
          tree -L 2 ${{ github.workspace }}

      - name: Extract winDist.tar.gz
        run: cd ./recaster && mkdir -p ./Stanag2WebRtc/win && tar -xzf ./winDist.tar.gz -C ./Stanag2WebRtc/win --strip-components=1

      - name: Print tree structure for Stanag2WebRtc directory
        run: tree ${{ github.workspace }}/recaster/Stanag2WebRtc/

      - name: List files in the repository
        run: |
          tree -L 3 ${{ github.workspace }}

          

