name: OnTest

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:

      - name: Install jq, unzip and 7zip
        run: |
          sudo apt-get install jq
          sudo apt-get install p7zip-full
          sudo apt-get install unzip

      - name: Get tag name
        id: get_tag
        run: |
          TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})
          echo "Tag name is: $TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          
      - name: Get Stanag2WebRtc release information
        id: get_release
        run: |
          tag_name="v2.0.0"
          release_info=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/impleotv/stanag2webrtc-release/releases/tags/$tag_name")
          release_id=$(echo $release_info | jq -r '.id')
          asset_url_linux=$(echo $release_info | jq -r '.assets[] | select(.name == "linuxDist.tar.gz") | .browser_download_url')
          asset_url_win=$(echo $release_info | jq -r '.assets[] | select(.name == "winDist.tar.gz") | .browser_download_url')
          echo "asset_url_linux=$asset_url_linux" >> $GITHUB_ENV
          echo "asset_url_win=$asset_url_win" >> $GITHUB_ENV
          echo "Linux asset URL: $asset_url_linux"
          echo "Windows asset URL: $asset_url_win"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# --------------------------------------------
      - name: Download winDist.tar.gz
        run: |
          cd ./recaster 
          wget "$asset_url_win" -O winDist.tar.gz
        env:
          asset_url_win: ${{ steps.get_release.outputs.asset_url_win }}
    
      - name: List files in the repository
        run: |
          tree -L 2 ${{ github.workspace }}

      - name: Extract LinuxDist.tar.gz
        run: cd ./recaster && mkdir -p ./Stanag2WebRtc/win && tar -xzf ./winDist.tar.gz -C ./Stanag2WebRtc/win --strip-components=1

      - name: Create Linux Release
        run: cd ./recaster && npm run create-installLinux

 



      - name: List files in the repository
        run: |
          tree -L 2 ${{ github.workspace }}


      - name: List files in the repository
        run: |
          tree -L 3 ${{ github.workspace }}

          
      - name: Print tree structure for Stanag2WebRtc directory
        run: tree ${{ github.workspace }}/recaster/Stanag2WebRtc/

