name: OnPushNewVersion

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout recaster
        uses: actions/checkout@v2
        with:
          repository: impleotv/recaster
          token: ${{ secrets.RECASTER_REPO_TOKEN }}
          path: ./recaster       
    
      # - name: List files in the repository
      #   run: |
      #     tree ${{ github.workspace }}

      - name: Setup NodeJs 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install mkdocs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-macros-plugin

      - name: Install dependencies
        run: cd ./recaster && npm install

      - name: Build Recaster
        run: cd ./recaster && npm run build_help

      - name: List files in the repository
        run: |
          tree -L 2 ${{ github.workspace }}

      - name: Install ftp-deploy
        run: npm install -g ftp-deploy

      - name: Deploy to FTP
        run: ftp-deploy --user ${{ secrets.FTP_CONTENT_USER }} --password ${{ secrets.FTP_CONTENT_PASSW }} --host ftp.impleotv.com --local-dir ./recaster/Doc/site --remote-dir /recaster/help
              
      - name: Clean up
        run: |
         rm -rf ./recaster


